name: publish

on:
  release:
    types: [ created ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'

      - name: npm install, npm run build
        run: |
          npm ci
          npm publish --access public

        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
